### PR TITLE
Properly fill in auth object for Android

### LINKED ISSUE #88: Unexpected format of the auth when talking to Android app
Was using firebase-server to test Android app for about 2 months now but not with the rules file (`-r`), i.e. every operation was allowed by default.
Today I wanted to improve my setup a bit and got stuck with authentication. Looks like the auth token coming from Android is not quite what firebase-server expects:

```
  firebase-server:token-validator decode(token: "<redacted>", secret: null) =>
{
  "iss":"https://securetoken.google.com/<app-name>",
  "provider_id":"anonymous",
  "aud":"<app-name>",
  "auth_time":1494740845,
  "user_id":"1p1VFLRdM2azwFqDNkW30i54QSU2",
  "sub":"1p1VFLRdM2azwFqDNkW30i54QSU2",
  "iat":1494740845,
  "exp":1494744445,
  "firebase":{"identities":{},"sign_in_provider":"anonymous"}
} +2ms
```
(indentation modified into a human readable form)

Replacing [line 116](https://github.com/urish/firebase-server/blob/0.10.0/index.js#L116) in `firebase-server/index.js`:

```javascript
data = server._tokenValidator.decode(authToken).d;
```

with

```javascript
data = {uid: server._tokenValidator.decode(authToken).user_id};
```

makes this token work indeed, but this doesn't seem like a right thing to do, and I don't have a JavaScript app with me to compare the formats. What do you think?

### PR DESCRIPTION
**Pull request by dotdoom**
The "auth" object is later used to do permission checks by the means of targaryen library [1].
I don't know the semantics of the token that JavaScript client sends, but [3] is for what Android sends in, and, given that JavaScript clients were tested to work correctly, I assume the format is different for some reason. The idea of this pull request is to bring the Android token in line with the official documentation at [2].

Why not make this change to targaryen library instead?
Well, the "auth" object supplied to targaryen is supposed to be of the format described in [2] rather than being protocol-bound, so firebase-server, as a protocol handler, is a more appropriate place to put an adapter in.

Fixes #88.

[1] https://github.com/goldibex/targaryen
[2] https://firebase.google.com/docs/reference/security/database/#auth
[3] https://github.com/urish/firebase-server/issues/88

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -112,8 +112,18 @@ FirebaseServer.prototype = {
...
 			if (authToken) {
+				var decodedToken;
 				try {
-					data = server._tokenValidator.decode(authToken).d;
+					decodedToken = server._tokenValidator.decode(authToken);
+					if ('d' in decodedToken) {
+						data = decodedToken.d;
+					} else {
+						data = {
+							uid: decodedToken.sub,
```
Comment (urish) [inline index.js]: per #88, wasn't it `user_id` instead of `sub` ?

**Comment by urish** [comment]
thanks, please have a look at my comment

File: index.js (hunk 1 above)
Comment (dotdoom) [inline index.js]: You are right.
Both have the same value, but `sub` is a standard JWT claim, while `user_id` is firebase-specific.
What if I use `sub` as a fallback for `user_id`?

**Comment by dotdoom** [comment]
Thanks for taking a look. Sorry for the diminished coverage: unfortunately, the token encryption in `firebase-token-generator` is bound to the generator that enforces `.d` field, and can not be reused to generate an Android token mentioned in #88.
Copy-pasting token encryption algorithm is possible, however I'm not sure you'd like to see such code in this repo.

**Comment by urish** [comment]
awesome, thanks!

**Comment by urish** [comment]
Released as 0.10.1
